name: Publish

on:
  push:
    branches:
      - master
      - dev

jobs:
  publish:
    uses: shoshin-packages/ci/.github/workflows/library-publish.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
