name: Test

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  test:
    uses: shoshin-packages/ci/.github/workflows/core-test.yml@main
    with:
      test-script: test
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
